# Generated by Django 3.2.9 on 2021-12-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('venue', models.CharField(max_length=100)),
                ('start_Date_Time', models.DateTimeField()),
                ('end_Date_Time', models.DateTimeField()),
            ],
        ),
    ]
