# Generated by Django 3.2.9 on 2022-01-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_hall', '0002_bookhall_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhall',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('declined', 'DECLINED')], default='pending', max_length=12),
        ),
    ]
