# Generated by Django 3.2.9 on 2022-01-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='societyinformation',
            name='registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyinformation',
            name='total_Area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
