# Generated by Django 3.2.9 on 2022-01-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
