# Generated by Django 3.2.9 on 2022-04-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
